import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css'; // Assuming a globals.css file exists or might be added later
import { Analytics } from "@vercel/analytics/next";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App', // You can change this default title
  description: 'Generated by create next app', // You can change this default description
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
